bot.pipelines=${BOT_PIPELINES:default-pipeline}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
jenkins.url=${JENKINS_URL}
jenkins.user=${JENKINS_USER}
jenkins.token=${JENKINS_TOKEN}
jenkins.trigger-token=${JENKINS_TRIGGER_TOKEN}